class VaultCreation {
  //Creates the vault with the contents generated by Security class
  String _salt;
  Map<String, String> _kdf;

  VaultCreation(this._salt, this._kdf);
  String createVaultFileStructure() {
    return "{}";
  }

  void readVaultFileStructure(String fileStructure) {
    _salt = "something here";
    _kdf = <String, String>{'General Kenobi': 'Hello there!'};
  }
}
