import 'dart:convert';
import 'dart:typed_data';

class VaultCreation {
  //Creates the vault with the contents generated by Security class
  static final List<String> _listOfRequiredKeysOfJson = [
    "vault",
    "version",
    "metadata",
    "payload",
    "nonce",
  ];

  static Map<String, dynamic> createVaultFileStructure(
    Map<String, String> metadata,
    Map<String, String> payload,
  ) {
    Map<String, dynamic> vaultStructure = {
      "vault": 1,
      "version": 1,
      "metadata": {},
      "payload": {"nonce": "", "ciphertext": "dummy_ciphertext"},
    };

    vaultStructure["metadata"] = metadata;
    vaultStructure["payload"] = payload;

    return vaultStructure;
  }

  static String convertUInt8ListToString(Uint8List filecontents) {
    return utf8.decode(filecontents);
  }

  static Uint8List convertMapToUInt8List<K, V extends Object?>(Map<K, V> map) {
    //Needs to be specified before so the compiler knows that K, V are generic, and extends is to specifiy is Object, which is the only required for JSON
    String data = jsonEncode(map);
    return utf8.encode(data);
  }

  static Map<String, dynamic> readVaultFileStructure(String fileStructure) {
    Map<String, dynamic> vaultFileContents;
    try {
      vaultFileContents = jsonDecode(fileStructure);
      for (var requiredKeyOfJSON in _listOfRequiredKeysOfJson) {
        if (!vaultFileContents.keys.contains(requiredKeyOfJSON)) {
          throw Exception(
            "The required key $requiredKeyOfJSON is not contain within the keys of the vault structure ${vaultFileContents.keys.toList()}",
          );
        }
      }
    } catch (e) {
      throw Exception("Corrupted vault structure!");
    }
    return vaultFileContents;
  }
}
