import 'dart:convert';

class VaultCreation {
  //Creates the vault with the contents generated by Security class
  String _salt;
  Map<String, dynamic> _vaultStructure;
  final List<String> _listOfRequiredKeysOfJson = [
    "vault",
    "version",
    "metadata",
    "payload",
    "nonce",
  ];

  VaultCreation({
    String salt = "something here",
    Map<String, String>? vaultStructure,
  }) : this._salt = salt,
       this._vaultStructure =
           vaultStructure ??
           {
             "vault": 1,
             "version": 1,
             "metadata": {},
             "payload": "",
             "nonce": "",
           };

  void createVaultFileStructure(Map<String, String> metadata, String payload) {
    //When vault creating the first time
    _vaultStructure["metadata"] = metadata;
    _vaultStructure["payload"] = payload;
  }

  void readVaultFileStructure(String fileStructure) {
    Map<String, dynamic> vaultFileContents;
    try {
      vaultFileContents = jsonDecode(fileStructure);
      for (var requiredKeyOfJSON in _listOfRequiredKeysOfJson) {
        if (!vaultFileContents.keys.contains(requiredKeyOfJSON)) {
          throw Exception(
            "The required key $requiredKeyOfJSON is not contain within the keys of the vault structure ${vaultFileContents.keys.toList()}",
          );
        }
      }
    } catch (e) {
      throw Exception("Corrupted vault structure!");
    }
  }
}
